FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD de-ds-docusign-template-library.jar /opt/de-ds-docusign-template-library/
EXPOSE 8080
WORKDIR /opt/de-ds-docusign-template-library/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "de-ds-docusign-template-library.jar"]
